env:
  - CODECLIMATE_REPO_TOKEN= ${{ secrets.CC_TEST_REPORTER_ID }}
language: python
python: 3.7

install: make

before_install:
  - pip install poetry

intstall:
  - make install

script:
  - make lint
  - make test
  - coverage report --fail-under=80

after_success:
  - codeclimate-test-reporter --file .coverage --upload
