env:
  global:
    - CC_TEST_REPORTER_ID=4567216710d386622d5910eed8485d56e5f22a894707fece56c0bbbdcbe513ed
language: python
python: 3.7

install: make

before_install:
  - pip install poetry

intstall:
  - make install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint
  - make test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

