env:
  - CODECOV_TOKEN=4567216710d386622d5910eed8485d56e5f22a894707fece56c0bbbdcbe513ed
language: python
python: 3.7

install: make

before_install:
  - pip install poetry
  - pip install codeclimate-test-reporter

intstall:
  - make install

script:
  - make lint
  - py.test --cov=gendiff tests

after_success:
  - codeclimate-test-reporter --file .coverage
