name: Python CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          make install
          poetry update --lock
      - name: Run linter and pytest
        run: |
          make check
          make lint
          make test
      - name: Upload  coverage to Codeclimate
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: 4567216710d386622d5910eed8485d56e5f22a894707fece56c0bbbdcbe513ed
        with:
          coverageCommand: .coverage after-build -d
