# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
    paths:
      - gendiff/*
      - test/*
      
jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        python-version: [3.7, 3.8]
    name: test/python-version ${{ matrix.python-version }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: pip install poetry
      - run: make install
      - run: make lint
      - run: make test
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: '3.7'
      - run: python -m pip install --upgrade pip
      - run: pip install poetry
      - run: make install
      - uses: paambaati/codeclimate-action@v2.5.7
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: codeclimate-test-reporter --file .coverage
          debug: true   


         
    
              
