# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
    paths:
      - gendiff/*
      - test/*
      
jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        python-version: [3.7, 3.8]
    name: test/python-version ${{ matrix.python-version }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
        
       
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        make install
    - name: Linter check
      run: |
        make lint
    - name: test
      run: |
        make test
    - name: Velocity deploy action
      uses: codeclimate/velocity-deploy-action@v1.0.0
      with:
         CODECLIMATE_REPO_TOKEN: 4567216710d386622d5910eed8485d56e5f22a894707fece56c0bbbdcbe513ed
     

         
    
              
